In [4]:
import torch
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [5]:
y = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
z = torch.zeros(3,2)
z

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
o = torch.ones(3,2)
o

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
r = torch.rand(2,2)
r

tensor([[0.6819, 0.1631],
        [0.5480, 0.2121]])

In [ ]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]
])

a.shape
ele = a[1,2]   # same as a[1][2]
ele

tensor(6)

In [13]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)
print(a * b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [ ]:
import numpy as np
arr = np.array([1,2,3])   # arr and n, both are pointing to the same location

n = torch.from_numpy(arr)  # converting a numpy array to a tensor
n

tensor([1, 2, 3])

In [16]:
x = torch.tensor([1.,2.,3.,4.])
y = torch.tensor([2.,4.,6.,8.])

m = torch.tensor(0.0)
c = torch.tensor(0.0)

y_pred = m * x + c
loss = ((y_pred - y) ** 2).mean()

print("Predicted Y : ", y_pred)
print("Loss : ",loss)

Predicted Y :  tensor([0., 0., 0., 0.])
Loss :  tensor(30.)
